import { describe, expect, it } from "vitest";
import type { WorkerConfig } from "../src/config";
import { resolveBoxEngineContext } from "../src/boxEngines";

function buildWorkerConfig(overrides?: Partial<WorkerConfig>): WorkerConfig {
  return {
    convexUrl: "https://example.convex.cloud",
    agentCommand: "openclaw",
    agentModel: "gpt-5.4",
    agentTimeoutMs: 600000,
    redisUrl: "redis://127.0.0.1:6379",
    artifactStorageProvider: "r2",
    artifactStorageLabel: "R2",
    r2Endpoint: "https://example.r2.cloudflarestorage.com",
    r2Bucket: "softbox-r2",
    r2AccessKeyId: "key",
    r2SecretAccessKey: "secret",
    publicDevelopmentUrl: "https://cdn.example.com",
    s3Api: "https://example.r2.cloudflarestorage.com/softbox-r2",
    appId: "vite-default",
    pollIntervalMs: 1500,
    staleJobTimeoutMs: 120000,
    queueName: "softbox-jobs",
    queueConcurrency: 1,
    queueAttempts: 2,
    queueBackoffMs: 800,
    r2UploadConcurrency: 6,
    projectRoot: "/tmp/softbox",
    openClawGatewayBaseUrl: "http://127.0.0.1:18789",
    openClawGatewayToken: "test-token",
    openClawAgentId: undefined,
    openClawAgentIdPrefix: "softbox-demo-",
    openClawSessionKeyPrefix: "softbox",
    ...overrides,
  };
}

describe("resolveBoxEngineContext", () => {
  it("prefers the configured provider profile model over the last observed box model", () => {
    const context = resolveBoxEngineContext({
      config: buildWorkerConfig(),
      appId: "vite-default",
      liveAppRoot: "/tmp/softbox/apps/vite-default",
      appConfig: {
        appId: "vite-default",
        name: "Vite Default",
        openClawSessionId: "session_123",
        box: {
          boxId: "openclaw:vite-default",
          subjectId: "vite-default",
          subjectKind: "app",
          appId: "vite-default",
          engine: "openclaw",
          engineProfileId: "openclaw:default",
          providerProfileId: "openai-codex:default",
          agentId: "softbox-demo-vite-default",
          targetPath: "/tmp/softbox/apps/vite-default",
          workspacePath: "/tmp/softbox/apps/vite-default",
          sessionId: "session_123",
          sessionKeyGeneration: 2,
          provider: "anthropic",
          model: "anthropic/claude-sonnet-4",
          status: "ready",
          policy: {},
          lastRunAt: Date.now(),
          lastError: null,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        boxes: [],
        primaryBox: {
          boxId: "openclaw:vite-default",
          subjectId: "vite-default",
          subjectKind: "app",
          appId: "vite-default",
          engine: "openclaw",
          engineProfileId: "openclaw:default",
          providerProfileId: "openai-codex:default",
          agentId: "softbox-demo-vite-default",
          targetPath: "/tmp/softbox/apps/vite-default",
          workspacePath: "/tmp/softbox/apps/vite-default",
          sessionId: "session_123",
          sessionKeyGeneration: 2,
          provider: "anthropic",
          model: "anthropic/claude-sonnet-4",
          status: "ready",
          policy: {},
          lastRunAt: Date.now(),
          lastError: null,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        engineProfile: {
          engineProfileId: "openclaw:default",
          engine: "openclaw",
          name: "OpenClaw Default",
          description: null,
          status: "ready",
          isDefault: true,
          config: {
            gatewayBaseUrl: "http://127.0.0.1:18789",
            routingMode: "per_app",
            sessionKeyPrefix: "softbox",
            agentId: null,
            agentIdPrefix: "softbox-demo-",
            tokenConfigured: true,
          },
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        providerProfile: {
          providerProfileId: "openai-codex:default",
          engineProfileId: "openclaw:default",
          provider: "openai-codex",
          name: "OpenAI Default",
          description: null,
          model: "openai-codex/gpt-5.4-mini",
          status: "ready",
          isDefault: true,
          config: {},
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
      },
    });

    expect(context).toMatchObject({
      provider: "openai-codex",
      model: "openai-codex/gpt-5.4-mini",
    });
  });
});
